"""Conversation history, stored in Supabase.

Talks to PostgREST over plain HTTP with `requests`, which the functions already
depend on. A dedicated client library would add bundle weight and cold start
time for four straightforward calls.

Two rules shape everything here:

  * **History is never allowed to break a chat turn.** Every call is wrapped and
    every failure is swallowed into a log line. A database outage, a bad key or
    a missing table degrades the product to "no history" rather than "no agent".
  * **The service role key never leaves the server.** It is read from the
    environment, sent only to the Supabase REST endpoint, and never returned in
    a response or written to a log.
"""

from __future__ import annotations

import os
import sys
from typing import Any

import requests

CONVERSATIONS = "agent_conversations"
TURNS = "agent_turns"


# Read on each call rather than captured at import. _agent is what loads the
# local .env files, and _routes imports this module first, so module-level
# constants would be read before those files had been applied and history would
# silently switch itself off during local development.
def _base_url() -> str:
    return (os.getenv("SUPABASE_URL") or "").rstrip("/")


def _service_key() -> str:
    return os.getenv("SUPABASE_SERVICE_ROLE_KEY") or ""

# Short on purpose. A serverless request already spent 5 to 15 seconds on the
# model; history must not be what pushes it past the function's time limit.
TIMEOUT_S = 6
TITLE_MAX = 120


def configured() -> bool:
    """True when both halves of the credential are present."""
    return bool(_base_url() and _service_key())


def _headers(extra: dict[str, str] | None = None) -> dict[str, str]:
    key = _service_key()
    headers = {
        "apikey": key,
        "Authorization": f"Bearer {key}",
        "Content-Type": "application/json",
    }
    if extra:
        headers.update(extra)
    return headers


def _log(message: str) -> None:
    # stderr, and never with the key or a row's contents in it.
    print(f"[history] {message}", file=sys.stderr)


def _request(method: str, path: str, **kwargs: Any) -> Any | None:
    if not configured():
        return None
    try:
        response = requests.request(
            method,
            f"{_base_url()}/rest/v1/{path}",
            headers=_headers(kwargs.pop("extra_headers", None)),
            timeout=TIMEOUT_S,
            **kwargs,
        )
    except requests.RequestException as exc:
        _log(f"{method} {path.split('?')[0]} failed: {type(exc).__name__}")
        return None

    if response.status_code >= 400:
        # The body can name a missing table or a policy problem, which is worth
        # seeing; it does not contain the key.
        _log(f"{method} {path.split('?')[0]} -> {response.status_code}: {response.text[:200]}")
        return None
    if not response.content:
        return []
    try:
        return response.json()
    except ValueError:
        return []


def _title_from(message: str) -> str:
    single_line = " ".join(message.split())
    return single_line[:TITLE_MAX] if single_line else "Untitled conversation"


def start_conversation(first_message: str, meta: dict[str, Any]) -> str | None:
    """Create a conversation row and return its id, or None if unavailable.

    The id is generated by the database rather than accepted from the client, so
    a caller cannot choose which row it writes into.
    """
    rows = _request(
        "POST",
        CONVERSATIONS,
        json={
            "title": _title_from(first_message),
            "artifact_version": meta.get("artifact_version"),
            "provider": meta.get("provider"),
            "model": meta.get("model"),
        },
        extra_headers={"Prefer": "return=representation"},
    )
    if isinstance(rows, list) and rows:
        return rows[0].get("id")
    return None


def record_turn(conversation_id: str, turn_index: int, message: str, result: dict[str, Any]) -> bool:
    """Append one turn. Returns whether it was stored."""
    artifact = result.get("artifact") or {}
    stored = _request(
        "POST",
        TURNS,
        json={
            "conversation_id": conversation_id,
            "turn_index": turn_index,
            "user_message": message,
            "status": result.get("status"),
            "reply": result.get("reply"),
            "assistant_text": result.get("assistant_text"),
            "error": result.get("error"),
            "structured_output": result.get("structured_output"),
            "rounds": result.get("rounds") or [],
            "tool_events": result.get("tool_events") or [],
            "spans": result.get("spans") or [],
            "duration_ms": result.get("duration_ms"),
            "retries": result.get("retries") or 0,
            "artifact_version": artifact.get("artifact_version"),
            "prompt_hash": artifact.get("prompt_hash"),
            "tools_hash": artifact.get("tools_hash"),
            "provider": result.get("provider"),
            "model": result.get("model"),
        },
        extra_headers={"Prefer": "return=minimal"},
    )
    return stored is not None


def list_conversations(limit: int = 50) -> list[dict[str, Any]]:
    """Newest first, without their turns: this feeds the history list."""
    limit = max(1, min(limit, 200))
    rows = _request(
        "GET",
        f"{CONVERSATIONS}?select=id,title,created_at,updated_at,turn_count,last_status,model"
        f"&order=updated_at.desc&limit={limit}",
    )
    return rows if isinstance(rows, list) else []


def load_conversation(conversation_id: str) -> dict[str, Any] | None:
    """One conversation with every turn, in order, for reopening it in the UI."""
    conversations = _request(
        "GET",
        f"{CONVERSATIONS}?id=eq.{conversation_id}&select=*&limit=1",
    )
    if not isinstance(conversations, list) or not conversations:
        return None
    turns = _request(
        "GET",
        f"{TURNS}?conversation_id=eq.{conversation_id}&select=*&order=turn_index.asc",
    )
    return {
        "conversation": conversations[0],
        "turns": turns if isinstance(turns, list) else [],
    }


def delete_conversation(conversation_id: str) -> bool:
    """Remove a conversation. Its turns go with it via on delete cascade."""
    return (
        _request("DELETE", f"{CONVERSATIONS}?id=eq.{conversation_id}") is not None
    )
